### ISSUE TITLE
xmonad lib subdirectory

### ISSUE THREAD

**Issue by joe9** [flycheck/flycheck-hdevtools#3]
Hello,

I need some advice on what would be the recommend way of dealing with the issue.

When editing xmonad.hs using flycheck-hdevtools, flycheck does not search the lib/ subdirectory for modules and throws the below error:

   69  18 error    Could not find module `XMonad.Util.DTrace'
    Perhaps you meant
      XMonad.Util.Image (from xmonad-contrib-0.12)
      XMonad.Util.Replace (from xmonad-contrib-0.12)
      XMonad.Util.Stack (from xmonad-contrib-0.12)
    Use -v to see a list of the files searched for. (haskell-hdevtools)

Below is the relevant recompile command in xmonad:

-- | 'recompile force', recompile @~\/.xmonad\/xmonad.hs@ when any of the
...
...
recompile :: MonadIO m => Bool -> m Bool
recompile force = io $ do
    dir <- getXMonadDir
    let binn = "xmonad-"++arch++"-"++os
        bin  = dir </> binn
        base = dir </> "xmonad"
        err  = base ++ ".errors"
        src  = base ++ ".hs"
        lib  = dir </> "lib"
    libTs <- mapM getModTime . Prelude.filter isSource =<< allFiles lib
    srcT <- getModTime src
    binT <- getModTime bin
    if force || any (binT <) (srcT : libTs)
      then do
        -- temporarily disable SIGCHLD ignoring:
        uninstallSignalHandlers
        status <- bracket (openFile err WriteMode) hClose $ \h ->
            waitForProcess =<< runProcess "ghc" ["--make", "xmonad.hs", "-i", "-ilib", "-fforce-recomp", "-main-is", "main", "-v0", "-o",binn] (Just dir)
                                    Nothing Nothing Nothing (Just h)

----- relevant hdevtools commands
hdevtools check -g -Wall xmonad.hs
xmonad.hs:69:18:
    Could not find module `XMonad.Util.DTrace'
    Perhaps you meant
      XMonad.Util.Image (from xmonad-contrib-0.12)
      XMonad.Util.Replace (from xmonad-contrib-0.12)
      XMonad.Util.Stack (from xmonad-contrib-0.12)
    Use -v to see a list of the files searched for.
-  -  -  -  -  -  -  -  -  -
hdevtools check -g -Wall -g -ilib xmonad.hs
xmonad.hs:230:1: Warning:
    Top-level binding with no type signature:
      myLayoutHook :: .....

Any thoughts, please?

I need to add a parameter to hdevtools. Not sure if it is a good idea to have it as a flycheck-hdevtools variable?

Thanks
Joe

**Comment by lunaryorn** [comment]
Closing due to the lack of activity.
