### ISSUE TITLE
hdevtools should use source-inplace, not source

### ISSUE THREAD

**Issue by fizbin** [flycheck/flycheck-hdevtools#9]
Hdevtools - which is in fact still being developed and worked on, as flaky as it may seem to be lately, has built-in support for finding cabal sandboxes, and using them.

Unfortunately, this support assumes that it will be given the actual path to the file (or enough of the path as is needed to crawl back up the tree to find the cabal sandbox).

This used to happen automatically, with `source-inplace`. However, for reasons I don't understand, `source-inplace` was replaced with `source` in mid-2014. This breaks the ability of hdevtools to find the local cabal sandbox, and makes it significantly less useful on actual haskell projects.

**Comment by purcell** [comment]
What about when there's no cabal sandbox, e.g. when using `stack`? Would there be any trade-offs for this change? If not, I'd be happy to have a pull request. I'm not using this myself right now, and can't promise to get around to changing it.

**Comment by fizbin** [comment]
Looking at the code, the same issue that keeps hdevtools from finding the cabal sandbox when using `source` instead of `source-inplace` would also keep it from finding `stack.yaml`.

That is, though I don't use stack myself, it appears from looking at the hdevtools source code that stack support would also be improved by using `source-inplace`.

PR incoming shortly...

**Comment by lunaryorn** [comment]
@purcell This appears to be fixed with d1cd10b05e184e64dcef721becce0491500e60f7?
